server {
    host 0.0.0.0
    ports 8080 8081
    server_name localhost
    client_max_body_size 1048576

    error_page 400 template/errors/400.html
    error_page 403 template/errors/403.html
    error_page 404 template/errors/404.html
    error_page 405 template/errors/405.html
    error_page 413 template/errors/413.html
    error_page 429 template/errors/429.html
    error_page 500 template/errors/500.html

    route / {
        methods GET POST DELETE
        root server/cgi-bin/
        cgi_ext .py
        cgi_path /usr/bin/python3
        autoindex off
    }
    route /old {
        methods GET
        redirect /
    }
}
