server {
    host 0.0.0.0
    port 8080
    port 8081
    server_name localhost
    client_max_body_size 1048576

    error_page 404 errors/404.html

    route / {
        methods GET POST DELETE
        root ./www
        index index.html
        cgi_ext .py
        cgi_path /usr/bin/python3
        autoindex off
    }
}

