server {
    host 0.0.0.0
    port 8080 8081
    server_name localhost
    client_max_body_size 1048576

    error_page 404 errors/404.html

    route / {
        methods GET POST DELETE
        page index.html
        cgi_ext .py
        cgi_path /usr/bin/python3
    }
}

